import React from "react";
import { NextPage } from "next";
import Head from "next/head";

const Contact: NextPage = (): JSX.Element => {
  return (
    <div>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <h1>Contact</h1>
    </div>
  );
};

export default Contact;
