import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = (): JSX.Element => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <h1>Home</h1>
    </div>
  );
};

export default Home;
